### ISSUE TITLE
Make pydantic validation friendlier, when loading a builder from a _quarto.yml file

### ISSUE THREAD

**Issue by machow** [machow/quartodoc#116]
Currently, our use of pydantic validation errors can get pretty cryptic. It would be nice if we could point to the area of the source file, where validation is failing, with a very friendly and humanly interpretable message.

**Comment by hamelsmu** [comment]
Pydantic doesn't always seem to kick in - if you have a top level config it will error in a different way.  For example, consider the below config:

```yaml
quartodoc:
  foo: bar
  style: pkgdown
  dir: api
...
```

Will result in this error

```
Traceback (most recent call last):
  File "/opt/anaconda3/bin/quartodoc", line 33, in <module>
    sys.exit(load_entry_point('quartodoc', 'console_scripts', 'quartodoc')())
  File "/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/hamel/github/quartodoc/quartodoc/__main__.py", line 52, in build
    builder = Builder.from_quarto_config(config)
  File "/Users/hamel/github/quartodoc/quartodoc/autosummary.py", line 593, in from_quarto_config
    return cls_builder(**{k: v for k, v in cfg.items() if k != "style"})
TypeError: __init__() got an unexpected keyword argument 'foo'
```

**Comment by hamelsmu** [comment]
I'm going to try and focus on the issue in https://github.com/machow/quartodoc/issues/138 that deals with situations when pydantic validation error is being raise

**Comment by machow** [comment]
I think right now we only feed part of the config in, but if it will help with giving better feedback, having pydantic serialize the full config seems like fair game.

(Similar, I'm not sure if pydantic gives better validation messages when serializing directly from json. But if it does, it also seems like fair game to somehow tap into that)

**Comment by machow** [comment]
From pairing, maybe it's possible to add line information using this approach?:

https://github.com/pydantic/pydantic/issues/1273#issuecomment-593472805

**Comment by machow** [comment]
implemented in https://github.com/machow/quartodoc/releases/tag/v0.3.4
