### ISSUE TITLE
Invalid config yaml in `_quarto.yml` produces confusing error messages

### ISSUE THREAD

**Issue by hamelsmu** [machow/quartodoc#138]
This is my YAML

```yml
project:
  type: website

website:
  sidebar: # see https://quarto.org/docs/reference/projects/websites.html#sidebar
      collapse-level: 2
      align: left
      contents: # see https://quarto.org/docs/websites/website-navigation.html#side-navigation
        - section: "Reference API"
          contents: "reference/**"

quartodoc:
  # the name used to import the package
  package: quartodoc
  sections:
    - title: Some functions
      kind: page
      desc: Functions to inspect docstrings.
      contents:
        - get_object
        - preview
```

this produces the following error:

```
Traceback (most recent call last):
  File "/opt/anaconda3/bin/quartodoc", line 8, in <module>
    sys.exit(cli())
  File "/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/quartodoc/__main__.py", line 52, in build
    builder = Builder.from_quarto_config(config)
  File "/opt/anaconda3/lib/python3.9/site-packages/quartodoc/autosummary.py", line 559, in from_quarto_config
    return cls_builder(**{k: v for k, v in cfg.items() if k != "style"})
  File "/opt/anaconda3/lib/python3.9/site-packages/quartodoc/autosummary.py", line 386, in __init__
    self.layout = self.load_layout(sections=sections, package=package)
  File "/opt/anaconda3/lib/python3.9/site-packages/quartodoc/autosummary.py", line 406, in load_layout
    return layout.Layout(sections=sections, package=package)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for Layout
sections -> 0 -> Page -> path
  field required (type=value_error.missing)
sections -> 0 -> kind
  unexpected value; permitted: 'section' (type=value_error.const; given=page; permitted=('section',))
```

What does this invalid config yaml have to do with Layouts and sections?  I think a proper error message should be thrown here.

**Comment by hamelsmu** [comment]
@machow I have made some progress sketching out a solution to this problem here: https://hamelsmu.github.io/pydantic-yaml-parser/

**Comment by machow** [comment]
From pairing, this approach seems great--and just seeing how you extend the parts makes it so clear what options we have for validation.

How about we add your custom validation to a `validation.py` file, and tests in `quartodoc/tests/test_validation.py`? That way, you can slot it in without worrying about changes to other files. 

If you add a function to validation.py called load_config or something, I think you should be able to slot it in [`Builder.load_layout`](https://github.com/machow/quartodoc/blob/main/quartodoc/autosummary.py#L449), or [Builder.from_quarto_config](https://github.com/machow/quartodoc/blob/main/quartodoc/autosummary.py#LL588C1-L588C1).

**Comment by machow** [comment]
Now gives this much nicer error, thanks to #116 !

<img width="900" alt="image" src="https://github.com/machow/quartodoc/assets/2574498/d1aa5085-29ae-45a7-bab1-f57d4a287c5a">
