### ISSUE TITLE
`dynamic` lookup is not able to find object and doesn't appear to work with class instances

### ISSUE THREAD

**Issue by hamelsmu** [machow/quartodoc#147]
I'm trying to test [Dynamic Lookups](https://machow.github.io/quartodoc/get-started/basic-content.html#dynamic-lookup) and using [`metaflow.current.current`](https://github.com/Netflix/metaflow/blob/master/metaflow/current.py#L296) as a test case.  My yaml looks like this:

```yaml
project:
  type: website
  pre-render:
    - "quartodoc build"

website:
  sidebar: # see https://quarto.org/docs/reference/projects/websites.html#sidebar
      collapse-level: 2
      align: left
      contents: # see https://quarto.org/docs/websites/website-navigation.html#side-navigation
        - section: "Reference API"
          contents: "reference/**"

quartodoc:
  package: metaflow
  sections:
    - title: Some functions
      desc: Functions to inspect docstrings.
      contents:
        - Flow
        - Run
        - name: current.current
          dynamic: true
```

This should work, but I get an error that says:

```
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/quartodoc/autosummary.py", line 270, in dynamic_alias
    crnt_part = getattr(crnt_part, attr_name)
AttributeError: 'Current' object has no attribute 'current'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/bin/quartodoc", line 8, in <module>
    sys.exit(cli())
  File "/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/quartodoc/__main__.py", line 59, in build
    builder.build(filter=filter)
  File "/opt/anaconda3/lib/python3.9/site-packages/quartodoc/autosummary.py", line 431, in build
    blueprint = blueprint(self.layout)
  File "/opt/anaconda3/lib/python3.9/site-packages/quartodoc/builder/blueprint.py", line 229, in blueprint
    return trans.visit(el)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 642, in __call__
    return self.f(self.instance, *args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 592, in __call__
    return _convert(method(*args, **kw_args), return_type)
  File "/opt/anaconda3/lib/python3.9/site-packages/quartodoc/builder/blueprint.py", line 74, in visit
    return super().visit(el)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 642, in __call__
    return self.f(self.instance, *args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 592, in __call__
    return _convert(method(*args, **kw_args), return_type)
  File "/opt/anaconda3/lib/python3.9/site-packages/quartodoc/builder/utils.py", line 45, in visit
    result = self.enter(el)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 642, in __call__
    return self.f(self.instance, *args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 592, in __call__
    return _convert(method(*args, **kw_args), return_type)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 592, in __call__
    return _convert(method(*args, **kw_args), return_type)
  File "/opt/anaconda3/lib/python3.9/site-packages/quartodoc/builder/utils.py", line 67, in enter
    result = self.visit(value)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 642, in __call__
    return self.f(self.instance, *args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 592, in __call__
    return _convert(method(*args, **kw_args), return_type)
  File "/opt/anaconda3/lib/python3.9/site-packages/quartodoc/builder/blueprint.py", line 74, in visit
    return super().visit(el)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 642, in __call__
    return self.f(self.instance, *args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 592, in __call__
    return _convert(method(*args, **kw_args), return_type)
  File "/opt/anaconda3/lib/python3.9/site-packages/quartodoc/builder/utils.py", line 45, in visit
    result = self.enter(el)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 642, in __call__
    return self.f(self.instance, *args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 592, in __call__
    return _convert(method(*args, **kw_args), return_type)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 592, in __call__
    return _convert(method(*args, **kw_args), return_type)
  File "/opt/anaconda3/lib/python3.9/site-packages/quartodoc/builder/utils.py", line 86, in enter
    result = self.visit(child)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 642, in __call__
    return self.f(self.instance, *args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 592, in __call__
    return _convert(method(*args, **kw_args), return_type)
  File "/opt/anaconda3/lib/python3.9/site-packages/quartodoc/builder/blueprint.py", line 74, in visit
    return super().visit(el)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 642, in __call__
    return self.f(self.instance, *args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 592, in __call__
    return _convert(method(*args, **kw_args), return_type)
  File "/opt/anaconda3/lib/python3.9/site-packages/quartodoc/builder/utils.py", line 45, in visit
    result = self.enter(el)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 642, in __call__
    return self.f(self.instance, *args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 592, in __call__
    return _convert(method(*args, **kw_args), return_type)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 592, in __call__
    return _convert(method(*args, **kw_args), return_type)
  File "/opt/anaconda3/lib/python3.9/site-packages/quartodoc/builder/utils.py", line 67, in enter
    result = self.visit(value)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 642, in __call__
    return self.f(self.instance, *args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 584, in __call__
    return method(*args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/quartodoc/builder/blueprint.py", line 74, in visit
    return super().visit(el)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 642, in __call__
    return self.f(self.instance, *args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 584, in __call__
    return method(*args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/quartodoc/builder/utils.py", line 45, in visit
    result = self.enter(el)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 642, in __call__
    return self.f(self.instance, *args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 586, in __call__
    return _convert(method(*args, **kw_args), return_type)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 584, in __call__
    return method(*args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/quartodoc/builder/utils.py", line 86, in enter
    result = self.visit(child)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 642, in __call__
    return self.f(self.instance, *args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 584, in __call__
    return method(*args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/quartodoc/builder/blueprint.py", line 74, in visit
    return super().visit(el)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 642, in __call__
    return self.f(self.instance, *args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 584, in __call__
    return method(*args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/quartodoc/builder/utils.py", line 45, in visit
    result = self.enter(el)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 642, in __call__
    return self.f(self.instance, *args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 584, in __call__
    return method(*args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/quartodoc/builder/blueprint.py", line 112, in enter
    obj = self.get_object_fixed(path, dynamic=el.dynamic)
  File "/opt/anaconda3/lib/python3.9/site-packages/quartodoc/builder/blueprint.py", line 58, in get_object_fixed
    return self.get_object(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/quartodoc/autosummary.py", line 137, in get_object
    return dynamic_alias(path, loader=loader)
  File "/opt/anaconda3/lib/python3.9/site-packages/quartodoc/autosummary.py", line 276, in dynamic_alias
    raise AttributeError(
AttributeError: No attribute named `current` in the path `metaflow:current.current`.
```

I think the limitation is that it wants to assume that it is an attribute because objects can only be nested one level deep?  As another step, the `current` object is also [available at the top level](https://github.com/Netflix/metaflow/blob/master/metaflow/__init__.py#L101) but even then dynamic lookup doesn't work here either.  So if I set my yaml like so, this should work, too:

```yaml
project:
  type: website
  pre-render:
    - "quartodoc build"

website:
  sidebar: # see https://quarto.org/docs/reference/projects/websites.html#sidebar
      collapse-level: 2
      align: left
      contents: # see https://quarto.org/docs/websites/website-navigation.html#side-navigation
        - section: "Reference API"
          contents: "reference/**"

quartodoc:
  package: metaflow
  sections:
    - title: Some functions
      desc: Functions to inspect docstrings.
      contents:
        - Flow
        - Run
        - name: current
          dynamic: true
```

But this doesn't work either!  I don't get an error in this case, but none of the class instance's methods, properties, etc are documented:

<img width="597" alt="image" src="https://github.com/machow/quartodoc/assets/1483922/6e07933f-7b00-42e3-8e6e-112c810b49b5">

**Comment by hamelsmu** [comment]
Still seeing this as an issue

<img width="867" alt="image" src="https://github.com/machow/quartodoc/assets/1483922/368631c4-eb81-4fd2-9934-6cadea66f272">

**Comment by machow** [comment]
Looking a bit more into this--this isn't something supported by other documentation tools, and I'm not sure quartodoc could support it either.

If I'm understanding, gist is that metaflow wants..

* to document the Current class methods, but
* show them as part of the documentation for a class instance (`current = Current()`)

It looks like [to do this currently](https://github.com/Netflix/metaflow-docs/blob/master/docs/api/current.ipynb), it just mocks `current` in its docs, by defining it as a class, and then documenting those class methods.

I realize this doesn't match exactly how the metaflow docs look, but I wonder if a workaround might be something like:

* document metaflow.current.Current
* mention that metaflow.current.current is an instance of Current
* (could do both these things on the same page)

The resulting documentation would be different, in that the signatures would be for e.g. `Current.is_running_flow`, rather than `current.is_running_flow`.

WDYT?

**Comment by machow** [comment]
I think since the metaflow docs at the time mocked a Current object specifically for their docs, it makes sense that it might be a case that is hard for documentation tools in general (documenting an class instance as if it's the class itself). Happy to reopen / look again
