### ISSUE TITLE
Cannot document metaflow decorator

### ISSUE THREAD

**Issue by hamelsmu** [machow/quartodoc#196]
For example look at the `metaflow` branch of [this repo](https://github.com/hamelsmu/fastcore-quartodoc/blob/metaflow/_quarto.yml):

```yaml
project:
  type: website

website:
  title: "."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

# tell quarto to read the generated sidebar
metadata-files:
  - _sidebar.yml

quartodoc:
  # the name used to import the package
  package: metaflow

  # write sidebar data to this file
  sidebar: _sidebar.yml

  sections:
    - title: General utilities
      desc: General purpose utilities.
      contents:
        # the functions being documented in the package.
        # you can refer to anything: class methods, modules, etc..
        - step
        - current
        - S3
    - title: Documentation utilities
      desc: Utilities for documentation.
      contents:
        - FlowSpec
    - title: Decorators
      desc: decorators for metaflow
      contents:
        - conda_base
      dynamic: true

  
```

The trouble seems to be with `conda_base`.  While you can import it like this:

```python
from metaflow import conda_base
```

However,  `quartodoc build` gives this error:

```
quartodoc build                                                                             (metaflow)fastcore-quartodoc
Traceback (most recent call last):
  File "/Users/hamel/github/quartodoc/quartodoc/builder/blueprint.py", line 59, in get_object_fixed
    return self.get_object(*args, **kwargs)
  File "/Users/hamel/github/quartodoc/quartodoc/autosummary.py", line 147, in get_object
    f_data = loader.modules_collection[griffe_path]
  File "/opt/anaconda3/lib/python3.9/site-packages/griffe/mixins.py", line 28, in __getitem__
    return self.members[parts[0]][parts[1:]]  # type: ignore[attr-defined]
  File "/opt/anaconda3/lib/python3.9/site-packages/griffe/mixins.py", line 27, in __getitem__
    return self.members[parts[0]]  # type: ignore[attr-defined]
KeyError: 'conda_base'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/bin/quartodoc", line 8, in <module>
    sys.exit(cli())
  File "/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/hamel/github/quartodoc/quartodoc/__main__.py", line 59, in build
    builder.build(filter=filter)
  File "/Users/hamel/github/quartodoc/quartodoc/autosummary.py", line 483, in build
    blueprint = blueprint(self.layout, dynamic=self.dynamic)
  File "/Users/hamel/github/quartodoc/quartodoc/builder/blueprint.py", line 237, in blueprint
    return trans.visit(el)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 642, in __call__
    return self.f(self.instance, *args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 592, in __call__
    return _convert(method(*args, **kw_args), return_type)
  File "/Users/hamel/github/quartodoc/quartodoc/builder/blueprint.py", line 75, in visit
    return super().visit(el)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 642, in __call__
    return self.f(self.instance, *args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 592, in __call__
    return _convert(method(*args, **kw_args), return_type)
  File "/Users/hamel/github/quartodoc/quartodoc/builder/utils.py", line 45, in visit
    result = self.enter(el)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 642, in __call__
    return self.f(self.instance, *args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 592, in __call__
    return _convert(method(*args, **kw_args), return_type)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 592, in __call__
    return _convert(method(*args, **kw_args), return_type)
  File "/Users/hamel/github/quartodoc/quartodoc/builder/utils.py", line 67, in enter
    result = self.visit(value)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 642, in __call__
    return self.f(self.instance, *args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 592, in __call__
    return _convert(method(*args, **kw_args), return_type)
  File "/Users/hamel/github/quartodoc/quartodoc/builder/blueprint.py", line 75, in visit
    return super().visit(el)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 642, in __call__
    return self.f(self.instance, *args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 592, in __call__
    return _convert(method(*args, **kw_args), return_type)
  File "/Users/hamel/github/quartodoc/quartodoc/builder/utils.py", line 45, in visit
    result = self.enter(el)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 642, in __call__
    return self.f(self.instance, *args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 592, in __call__
    return _convert(method(*args, **kw_args), return_type)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 592, in __call__
    return _convert(method(*args, **kw_args), return_type)
  File "/Users/hamel/github/quartodoc/quartodoc/builder/utils.py", line 86, in enter
    result = self.visit(child)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 642, in __call__
    return self.f(self.instance, *args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 584, in __call__
    return method(*args, **kw_args)
  File "/Users/hamel/github/quartodoc/quartodoc/builder/blueprint.py", line 75, in visit
    return super().visit(el)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 642, in __call__
    return self.f(self.instance, *args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 584, in __call__
    return method(*args, **kw_args)
  File "/Users/hamel/github/quartodoc/quartodoc/builder/utils.py", line 45, in visit
    result = self.enter(el)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 642, in __call__
    return self.f(self.instance, *args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 586, in __call__
    return _convert(method(*args, **kw_args), return_type)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 584, in __call__
    return method(*args, **kw_args)
  File "/Users/hamel/github/quartodoc/quartodoc/builder/utils.py", line 67, in enter
    result = self.visit(value)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 642, in __call__
    return self.f(self.instance, *args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 584, in __call__
    return method(*args, **kw_args)
  File "/Users/hamel/github/quartodoc/quartodoc/builder/blueprint.py", line 75, in visit
    return super().visit(el)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 642, in __call__
    return self.f(self.instance, *args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 584, in __call__
    return method(*args, **kw_args)
  File "/Users/hamel/github/quartodoc/quartodoc/builder/utils.py", line 45, in visit
    result = self.enter(el)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 642, in __call__
    return self.f(self.instance, *args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 586, in __call__
    return _convert(method(*args, **kw_args), return_type)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 584, in __call__
    return method(*args, **kw_args)
  File "/Users/hamel/github/quartodoc/quartodoc/builder/utils.py", line 86, in enter
    result = self.visit(child)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 642, in __call__
    return self.f(self.instance, *args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 584, in __call__
    return method(*args, **kw_args)
  File "/Users/hamel/github/quartodoc/quartodoc/builder/blueprint.py", line 75, in visit
    return super().visit(el)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 642, in __call__
    return self.f(self.instance, *args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 584, in __call__
    return method(*args, **kw_args)
  File "/Users/hamel/github/quartodoc/quartodoc/builder/utils.py", line 45, in visit
    result = self.enter(el)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 642, in __call__
    return self.f(self.instance, *args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 584, in __call__
    return method(*args, **kw_args)
  File "/Users/hamel/github/quartodoc/quartodoc/builder/blueprint.py", line 115, in enter
    obj = self.get_object_fixed(path, dynamic=dynamic)
  File "/Users/hamel/github/quartodoc/quartodoc/builder/blueprint.py", line 61, in get_object_fixed
    raise WorkaroundKeyError(e.args[0])
quartodoc.builder.utils.WorkaroundKeyError: conda_base
```

**Comment by machow** [comment]
It looks like dynamic is being set on the section entry rather than the content entry for conda_base. Can you try setting the dynamic option like this?

https://machow.github.io/quartodoc/get-started/basic-content.html#dynamic-lookup

```
contents:
  - name: conda_base
    dynamic: true
```

I think the main issue is that pydantic allows extra fields in the config, so doesn't complain when dynamic is added to section (it just discards that data :/)

**Comment by machow** [comment]
From pairing w/ Hamel, it looks like...

* `conda_base` is a functools.partial object. Our dynamic load fails, because we try to get the `__module__` attribute off of it. We should be more robust here, or give a better error.
* partial objects have the partial class's doc as `__doc__`, so likely won't give the docstring people want
* it would be nice to point `conda_base()` at another functions, like `metaflow.plugins.conda.conda_flow_decorator.CondaFlowDecorator`
  - I.e. the documentation for `conda_base()` would essentially be the contents of CondaFlowDecorator

**Comment by hamelsmu** [comment]
Still getting an error here.  

I can successfully run this command:
```
 python -c "from metaflow import conda_base"
```

This is my `_quarto.yml` file:

```yaml
project:
  type: website

website:
  title: "."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

# tell quarto to read the generated sidebar
metadata-files:
  - _sidebar.yml

quartodoc:
  # the name used to import the package
  package: metaflow

  # write sidebar data to this file
  sidebar: _sidebar.yml

  sections:
    - title: General utilities
      desc: General purpose utilities.
      contents:
        # the functions being documented in the package.
        # you can refer to anything: class methods, modules, etc..
        - step
        - current
        - S3
    - title: Documentation utilities
      desc: Utilities for documentation.
      contents:
        - FlowSpec
    - title: Decorators
      desc: decorators for metaflow
      contents:
      - name: conda_base
        dynamic: true
```

When I run `quartodoc build` I get this error:


```
Traceback (most recent call last):
  File "/Users/hamel/github/quartodoc/quartodoc/builder/blueprint.py", line 154, in get_object_fixed
    return self.get_object(path, **kwargs)
  File "/Users/hamel/github/quartodoc/quartodoc/autosummary.py", line 144, in get_object
    return dynamic_alias(path, loader=loader)
  File "/Users/hamel/github/quartodoc/quartodoc/autosummary.py", line 327, in dynamic_alias
    obj = get_object(canonical_path, loader=loader)
  File "/Users/hamel/github/quartodoc/quartodoc/autosummary.py", line 148, in get_object
    f_data = loader.modules_collection[griffe_path]
  File "/opt/anaconda3/lib/python3.9/site-packages/griffe/mixins.py", line 28, in __getitem__
    return self.members[parts[0]][parts[1:]]  # type: ignore[attr-defined]
  File "/opt/anaconda3/lib/python3.9/site-packages/griffe/mixins.py", line 27, in __getitem__
    return self.members[parts[0]]  # type: ignore[attr-defined]
KeyError: 'conda_base'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/bin/quartodoc", line 8, in <module>
    sys.exit(cli())
  File "/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/hamel/github/quartodoc/quartodoc/__main__.py", line 209, in build
    doc_build()
  File "/Users/hamel/github/quartodoc/quartodoc/autosummary.py", line 499, in build
    blueprint = blueprint(self.layout, dynamic=self.dynamic, parser=self.parser)
  File "/Users/hamel/github/quartodoc/quartodoc/builder/blueprint.py", line 415, in blueprint
    return trans.visit(el)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 642, in __call__
    return self.f(self.instance, *args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 592, in __call__
    return _convert(method(*args, **kw_args), return_type)
  File "/Users/hamel/github/quartodoc/quartodoc/builder/blueprint.py", line 190, in visit
    return super().visit(el)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 642, in __call__
    return self.f(self.instance, *args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 592, in __call__
    return _convert(method(*args, **kw_args), return_type)
  File "/Users/hamel/github/quartodoc/quartodoc/builder/utils.py", line 45, in visit
    result = self.enter(el)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 642, in __call__
    return self.f(self.instance, *args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 592, in __call__
    return _convert(method(*args, **kw_args), return_type)
  File "/Users/hamel/github/quartodoc/quartodoc/builder/blueprint.py", line 227, in enter
    return super().enter(el)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 642, in __call__
    return self.f(self.instance, *args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 592, in __call__
    return _convert(method(*args, **kw_args), return_type)
  File "/Users/hamel/github/quartodoc/quartodoc/builder/utils.py", line 67, in enter
    result = self.visit(value)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 642, in __call__
    return self.f(self.instance, *args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 592, in __call__
    return _convert(method(*args, **kw_args), return_type)
  File "/Users/hamel/github/quartodoc/quartodoc/builder/blueprint.py", line 190, in visit
    return super().visit(el)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 642, in __call__
    return self.f(self.instance, *args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 592, in __call__
    return _convert(method(*args, **kw_args), return_type)
  File "/Users/hamel/github/quartodoc/quartodoc/builder/utils.py", line 45, in visit
    result = self.enter(el)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 642, in __call__
    return self.f(self.instance, *args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 592, in __call__
    return _convert(method(*args, **kw_args), return_type)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 592, in __call__
    return _convert(method(*args, **kw_args), return_type)
  File "/Users/hamel/github/quartodoc/quartodoc/builder/utils.py", line 86, in enter
    result = self.visit(child)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 642, in __call__
    return self.f(self.instance, *args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 584, in __call__
    return method(*args, **kw_args)
  File "/Users/hamel/github/quartodoc/quartodoc/builder/blueprint.py", line 190, in visit
    return super().visit(el)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 642, in __call__
    return self.f(self.instance, *args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 584, in __call__
    return method(*args, **kw_args)
  File "/Users/hamel/github/quartodoc/quartodoc/builder/utils.py", line 45, in visit
    result = self.enter(el)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 642, in __call__
    return self.f(self.instance, *args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 586, in __call__
    return _convert(method(*args, **kw_args), return_type)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 584, in __call__
    return method(*args, **kw_args)
  File "/Users/hamel/github/quartodoc/quartodoc/builder/utils.py", line 67, in enter
    result = self.visit(value)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 642, in __call__
    return self.f(self.instance, *args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 584, in __call__
    return method(*args, **kw_args)
  File "/Users/hamel/github/quartodoc/quartodoc/builder/blueprint.py", line 190, in visit
    return super().visit(el)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 642, in __call__
    return self.f(self.instance, *args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 584, in __call__
    return method(*args, **kw_args)
  File "/Users/hamel/github/quartodoc/quartodoc/builder/utils.py", line 45, in visit
    result = self.enter(el)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 642, in __call__
    return self.f(self.instance, *args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 586, in __call__
    return _convert(method(*args, **kw_args), return_type)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 584, in __call__
    return method(*args, **kw_args)
  File "/Users/hamel/github/quartodoc/quartodoc/builder/utils.py", line 86, in enter
    result = self.visit(child)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 642, in __call__
    return self.f(self.instance, *args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 584, in __call__
    return method(*args, **kw_args)
  File "/Users/hamel/github/quartodoc/quartodoc/builder/blueprint.py", line 190, in visit
    return super().visit(el)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 642, in __call__
    return self.f(self.instance, *args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 584, in __call__
    return method(*args, **kw_args)
  File "/Users/hamel/github/quartodoc/quartodoc/builder/utils.py", line 45, in visit
    result = self.enter(el)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 642, in __call__
    return self.f(self.instance, *args, **kw_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/plum/function.py", line 584, in __call__
    return method(*args, **kw_args)
  File "/Users/hamel/github/quartodoc/quartodoc/builder/blueprint.py", line 276, in enter
    obj = self.get_object_fixed(path, dynamic=dynamic)
  File "/Users/hamel/github/quartodoc/quartodoc/builder/blueprint.py", line 157, in get_object_fixed
    raise WorkaroundKeyError(
quartodoc.builder.utils.WorkaroundKeyError: Cannot find an object named: conda_base. Does an object with the path metaflow:conda_base exist?
```

**Comment by machow** [comment]
The code to import `conda_base` into the top-level metaflow looks highly dynamic. I think it would need to be referenced using its source module (or a point at which it's not dynamically imported).

It seems like maybe--similar to the way [its handled in the metaflow documentation](https://github.com/Netflix/metaflow-docs/blob/master/docs/api/flow-decorators/conda_base.ipynb)--you might need to...

* import it
* parse its docstring using griffe
* manually render (e.g. `from quartodoc import MdRenderer; MdRenderer().render(some_parsed_docstring)`)

I think the way the metaflow docs are laid out makes sense--and very user friendly--but its level of dynamism / focus on documenting instances vs classes mean it's unlikely the above can be supported soon :/.

**Comment by machow** [comment]
The level of dynamism / mocking in the metaflow docs makes it a bit hard to track. I'm going to close for now, but am happy to reopen
