### ISSUE TITLE
bug: unbound local variable when `show_signature_annotations: true`

### ISSUE THREAD

**Issue by isabelizimm** [machow/quartodoc#361]
Traceback

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/isabelzimmerman/.pyenv/versions/3.11.4/envs/vetiver/lib/python3.11/site-packages/quartodoc/__main__.py", line 283, in <module>
    cli()
  File "/Users/isabelzimmerman/.pyenv/versions/3.11.4/envs/vetiver/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/isabelzimmerman/.pyenv/versions/3.11.4/envs/vetiver/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/isabelzimmerman/.pyenv/versions/3.11.4/envs/vetiver/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/isabelzimmerman/.pyenv/versions/3.11.4/envs/vetiver/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/isabelzimmerman/.pyenv/versions/3.11.4/envs/vetiver/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/isabelzimmerman/.pyenv/versions/3.11.4/envs/vetiver/lib/python3.11/site-packages/quartodoc/__main__.py", line 219, in build
    doc_build()
  File "/Users/isabelzimmerman/.pyenv/versions/3.11.4/envs/vetiver/lib/python3.11/site-packages/quartodoc/autosummary.py", line 570, in build
    self.write_doc_pages(pages, filter)
  File "/Users/isabelzimmerman/.pyenv/versions/3.11.4/envs/vetiver/lib/python3.11/site-packages/quartodoc/autosummary.py", line 622, in write_doc_pages
    rendered = self.renderer.render(page)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/isabelzimmerman/.pyenv/versions/3.11.4/envs/vetiver/lib/python3.11/site-packages/plum/function.py", line 484, in __call__
    return self._f(self._instance, *args, **kw_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/isabelzimmerman/.pyenv/versions/3.11.4/envs/vetiver/lib/python3.11/site-packages/plum/function.py", line 368, in __call__
    return _convert(method(*args, **kw_args), return_type)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/isabelzimmerman/.pyenv/versions/3.11.4/envs/vetiver/lib/python3.11/site-packages/quartodoc/renderers/md_renderer.py", line 301, in render
    return "\n\n".join([*header, *result])
                       ^^^^^^^^^^^^^^^^^^
  File "/Users/isabelzimmerman/.pyenv/versions/3.11.4/envs/vetiver/lib/python3.11/site-packages/plum/function.py", line 484, in __call__
    return self._f(self._instance, *args, **kw_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/isabelzimmerman/.pyenv/versions/3.11.4/envs/vetiver/lib/python3.11/site-packages/plum/function.py", line 368, in __call__
    return _convert(method(*args, **kw_args), return_type)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/isabelzimmerman/.pyenv/versions/3.11.4/envs/vetiver/lib/python3.11/site-packages/quartodoc/renderers/md_renderer.py", line 424, in render
    [self.render(x) for x in raw_meths if isinstance(x, layout.Doc)]
  File "/Users/isabelzimmerman/.pyenv/versions/3.11.4/envs/vetiver/lib/python3.11/site-packages/quartodoc/renderers/md_renderer.py", line 424, in <listcomp>
    [self.render(x) for x in raw_meths if isinstance(x, layout.Doc)]
     ^^^^^^^^^^^^^^
  File "/Users/isabelzimmerman/.pyenv/versions/3.11.4/envs/vetiver/lib/python3.11/site-packages/plum/function.py", line 484, in __call__
    return self._f(self._instance, *args, **kw_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/isabelzimmerman/.pyenv/versions/3.11.4/envs/vetiver/lib/python3.11/site-packages/plum/function.py", line 368, in __call__
    return _convert(method(*args, **kw_args), return_type)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/isabelzimmerman/.pyenv/versions/3.11.4/envs/vetiver/lib/python3.11/site-packages/quartodoc/renderers/md_renderer.py", line 441, in render
    str_sig = self.signature(el)
              ^^^^^^^^^^^^^^^^^^
  File "/Users/isabelzimmerman/.pyenv/versions/3.11.4/envs/vetiver/lib/python3.11/site-packages/plum/function.py", line 484, in __call__
    return self._f(self._instance, *args, **kw_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/isabelzimmerman/.pyenv/versions/3.11.4/envs/vetiver/lib/python3.11/site-packages/plum/function.py", line 368, in __call__
    return _convert(method(*args, **kw_args), return_type)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/isabelzimmerman/.pyenv/versions/3.11.4/envs/vetiver/lib/python3.11/site-packages/quartodoc/renderers/md_renderer.py", line 228, in signature
    res = self.signature(el.obj)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/isabelzimmerman/.pyenv/versions/3.11.4/envs/vetiver/lib/python3.11/site-packages/plum/function.py", line 484, in __call__
    return self._f(self._instance, *args, **kw_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/isabelzimmerman/.pyenv/versions/3.11.4/envs/vetiver/lib/python3.11/site-packages/plum/function.py", line 368, in __call__
    return _convert(method(*args, **kw_args), return_type)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/isabelzimmerman/.pyenv/versions/3.11.4/envs/vetiver/lib/python3.11/site-packages/quartodoc/renderers/md_renderer.py", line 235, in signature
    return self.signature(el.final_target, el)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/isabelzimmerman/.pyenv/versions/3.11.4/envs/vetiver/lib/python3.11/site-packages/plum/function.py", line 484, in __call__
    return self._f(self._instance, *args, **kw_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/isabelzimmerman/.pyenv/versions/3.11.4/envs/vetiver/lib/python3.11/site-packages/plum/function.py", line 368, in __call__
    return _convert(method(*args, **kw_args), return_type)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/isabelzimmerman/.pyenv/versions/3.11.4/envs/vetiver/lib/python3.11/site-packages/quartodoc/renderers/md_renderer.py", line 242, in signature
    pars = self.render(self._fetch_method_parameters(el))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/isabelzimmerman/.pyenv/versions/3.11.4/envs/vetiver/lib/python3.11/site-packages/plum/function.py", line 484, in __call__
    return self._f(self._instance, *args, **kw_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/isabelzimmerman/.pyenv/versions/3.11.4/envs/vetiver/lib/python3.11/site-packages/plum/function.py", line 368, in __call__
    return _convert(method(*args, **kw_args), return_type)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/isabelzimmerman/.pyenv/versions/3.11.4/envs/vetiver/lib/python3.11/site-packages/quartodoc/renderers/md_renderer.py", line 502, in render
    pars = list(map(self.render, el))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/isabelzimmerman/.pyenv/versions/3.11.4/envs/vetiver/lib/python3.11/site-packages/plum/function.py", line 484, in __call__
    return self._f(self._instance, *args, **kw_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/isabelzimmerman/.pyenv/versions/3.11.4/envs/vetiver/lib/python3.11/site-packages/plum/function.py", line 368, in __call__
    return _convert(method(*args, **kw_args), return_type)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/isabelzimmerman/.pyenv/versions/3.11.4/envs/vetiver/lib/python3.11/site-packages/quartodoc/renderers/md_renderer.py", line 547, in render
    return res
           ^^^
UnboundLocalError: cannot access local variable 'res' where it is not associated with a value

```

**Comment by machow** [comment]
should be resolved in v0.8.0
