### ISSUE TITLE
Error with Quarto 1.3.294 and callouts

### ISSUE THREAD

**Issue by wch** [machow/quartodoc#82]
For example, here is a file `test.qmd`:

```md
---
title: "Test"
---

:::{.callout-note}
In these UI examples there's no server logic, so we're just using `None` instead of a server function.
:::
```

And this `_quarto.yml` file:

```yaml
project:
  type: website
  render:
    - /test.qmd

filters:
  - interlinks
```

With Quarto 1.3.294, this is what happens:

```
$ quarto render
pandoc 
  to: html
  output-file: test.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  title: Input controls
  
Error running filter /Users/winston/nobackup/quarto-cli/src/resources/filters/main.lua:
Block expected, got Attr
	while retrieving MetaValue
	while retrieving value
	while retrieving key-value pair
	while retrieving Map
	while retrieving MetaValue
	while retrieving value
	while retrieving key-value pair
	while retrieving Map
	while retrieving MetaValue
	while retrieving index 1
	while retrieving list
	while retrieving function argument values
	while retrieving arguments for function MetaList
stack traceback:
	...to-cli/src/resources/filters/./common/wrapped-filter.lua:79: in function <...to-cli/src/resources/filters/./common/wrapped-filter.lua:77>
	[C]: in ?
	[C]: in method 'walk'
	...to-cli/src/resources/filters/./common/wrapped-filter.lua:69: in function <...to-cli/src/resources/filters/./common/wrapped-filter.lua:64>
	[C]: in ?
	[C]: in method 'walk'
	...p/quarto-cli/src/resources/filters/./ast/customnodes.lua:140: in function 'run_emulated_filter'
	.../quarto-cli/src/resources/filters/./ast/runemulation.lua:11: in local 'callback'
	.../quarto-cli/src/resources/filters/./ast/runemulation.lua:16: in upvalue 'run_emulated_filter_chain'
	.../quarto-cli/src/resources/filters/./ast/runemulation.lua:57: in function <.../quarto-cli/src/resources/filters/./ast/runemulation.lua:38>
stack traceback:
	...to-cli/src/resources/filters/./common/wrapped-filter.lua:69: in function <...to-cli/src/resources/filters/./common/wrapped-filter.lua:64>
	[C]: in ?
	[C]: in method 'walk'
	...p/quarto-cli/src/resources/filters/./ast/customnodes.lua:140: in function 'run_emulated_filter'
	.../quarto-cli/src/resources/filters/./ast/runemulation.lua:11: in local 'callback'
	.../quarto-cli/src/resources/filters/./ast/runemulation.lua:16: in upvalue 'run_emulated_filter_chain'
	.../quarto-cli/src/resources/filters/./ast/runemulation.lua:57: in function <.../quarto-cli/src/resources/filters/./ast/runemulation.lua:38>
stack traceback:
	...p/quarto-cli/src/resources/filters/./ast/customnodes.lua:140: in function 'run_emulated_filter'
	.../quarto-cli/src/resources/filters/./ast/runemulation.lua:11: in local 'callback'
	.../quarto-cli/src/resources/filters/./ast/runemulation.lua:16: in upvalue 'run_emulated_filter_chain'
	.../quarto-cli/src/resources/filters/./ast/runemulation.lua:57: in function <.../quarto-cli/src/resources/filters/./ast/runemulation.lua:38>
ERROR: Error
    at renderFiles (file:///Users/winston/nobackup/quarto-cli/src/command/render/render-files.ts:538:23)
    at async renderProject (file:///Users/winston/nobackup/quarto-cli/src/command/render/project.ts:263:23)
    at async Command.fn (file:///Users/winston/nobackup/quarto-cli/src/command/render/cmd.ts:211:26)
    at async Command.execute (file:///Users/winston/nobackup/quarto-cli/src/vendor/deno.land/x/cliffy@v0.25.4/command/command.ts:1790:7)
    at async quarto (file:///Users/winston/nobackup/quarto-cli/src/quarto.ts:122:3)
    at async file:///Users/winston/nobackup/quarto-cli/src/quarto.ts:154:5
```

With Quarto 1.2.313, it ran fine.

Also, why is the extension called `interlinks` when I installed it with `quarto install extension machow/quartodoc`?

**Comment by cscheid** [comment]
Can you share a repo with all files needed to repro this? Thanks.

**Comment by wch** [comment]
https://github.com/wch/quarto-interlinks-error

**Comment by cscheid** [comment]
Yeah, this is a bug on quarto, thanks for the report. This only happens on non-lua filters (which `quartodoc` is, I believe, the lone consumer of :)). Sorry about that! We'll fix and add a regression test to prevent it to recur.

**Comment by cscheid** [comment]
@machow I think we have a bigger problem, which is how to let you communicate a change in the content of a callout or tabset. Right now, those features are kind of off-limits to non-lua filters (and I don't know how to make it work great for you).

You can inspect the contents we give you (you'll see it in the metadata, under `quarto-custom-nodes`). But the format is pretty wonky and quarto won't actually honor changes you make to those. That's unfortunately not something we'll be able to fix for 1.3/

**Comment by machow** [comment]
Ah thanks! I sent a calendar invite :).

I think the interlinks filter could likely be re-written in lua now. Its behavior seems pretty clear, and the weird part (converting sphinx `.inv` files to `.json` is now handled separately by running a quartodoc command beforehand). 

@wch does it work to build against quarto v1.2 for now? I think there are a number of workarounds (including turning off interlinks and resolving links directly in the renderer), but want to make sure you wouldn't be blocked by working in v1.2.

**Comment by machow** [comment]
Does it work if you run `python -m quartodoc build --verbose` first? I've added an issue for the interlinks filter to be more helpful with its error message..!

**Comment by wch** [comment]
I get another error:

```
$ python -m quartodoc build --verbose
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/winston/quarto-interlinks-error/venv/lib/python3.11/site-packages/quartodoc/__main__.py", line 95, in <module>
    cli()
  File "/Users/winston/quarto-interlinks-error/venv/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/winston/quarto-interlinks-error/venv/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/winston/quarto-interlinks-error/venv/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/winston/quarto-interlinks-error/venv/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/winston/quarto-interlinks-error/venv/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/winston/quarto-interlinks-error/venv/lib/python3.11/site-packages/quartodoc/__main__.py", line 51, in build
    builder = Builder.from_quarto_config(config)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/winston/quarto-interlinks-error/venv/lib/python3.11/site-packages/quartodoc/autosummary.py", line 394, in from_quarto_config
    cfg = quarto_cfg["quartodoc"]
          ~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'quartodoc'
```

**Comment by machow** [comment]
Where are you running from? Is there a quartodoc config in your `_quarto.yml`?

https://machow.github.io/quartodoc/get-started/overview.html#basic-use

**Comment by wch** [comment]
Oh, duh, I forgot to add that the `_quarto.yml` file. Now it works.

**Comment by cscheid** [comment]
In the meantime, the [latest 1.3 RC](https://github.com/quarto-dev/quarto-cli/releases/tag/v1.3.299) should work.

**Comment by wch** [comment]
@cscheid With 1.3 RC, I still get an error. Note that I have pushed some changes to the https://github.com/wch/quarto-interlinks-error repo since earlier today. After doing a `deactivate` and `git clean -xdi`, I re-ran the instructions in that repo's README and this is what I got.

I'm using quarto-cli at tag `v1.3.299` AKA https://github.com/quarto-dev/quarto-cli/commit/a7b2a41a75c0501c47640b608d9676d67c024411 and running using the git checkout; I'm not using the release .pkg, if that matters.

```
$ quarto render
pandoc 
  to: html
  output-file: test.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  interlinks:
    sources:
      python:
        url: 'https://docs.python.org/3/'
  quartodoc:
    style: single-page
    dir: reference
    package: quartodoc
    sections:
      - title: Some functions
        desc: Functions to inspect docstrings.
        contents:
          - get_object
          - preview
  title: Input controls
  
Traceback (most recent call last):
  File "/Users/winston/quarto-interlinks-error/_extensions/machow/interlinks/interlinks.py", line 274, in <module>
    main()
  File "/Users/winston/quarto-interlinks-error/_extensions/machow/interlinks/interlinks.py", line 270, in main
    return pf.run_filter(visit, prepare=prepare, doc=None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/winston/quarto-interlinks-error/venv/lib/python3.11/site-packages/panflute/io.py", line 227, in run_filter
    return run_filters([action], *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/winston/quarto-interlinks-error/venv/lib/python3.11/site-packages/panflute/io.py", line 200, in run_filters
    doc = load(input_stream=input_stream)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/winston/quarto-interlinks-error/venv/lib/python3.11/site-packages/panflute/io.py", line 58, in load
    doc = json.load(input_stream, object_hook=from_json)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/winston/quarto-interlinks-error/venv/lib/python3.11/site-packages/panflute/elements.py", line 1424, in from_json
    assert (len(data) == 1) or (len(data) == 2 and 'c' in data)
                                                   ^^^^^^^^^^^
AssertionError
Error running filter /Users/winston/nobackup/quarto-cli/src/resources/filters/main.lua:
Error running filter /Users/winston/quarto-interlinks-error/_extensions/machow/interlinks/interlinks.py:
Filter returned error status 1
stack traceback:
	...to-cli/src/resources/filters/./common/wrapped-filter.lua:114: in function <...to-cli/src/resources/filters/./common/wrapped-filter.lua:93>
	[C]: in ?
	[C]: in method 'walk'
	...p/quarto-cli/src/resources/filters/./ast/customnodes.lua:150: in function 'run_emulated_filter'
	.../quarto-cli/src/resources/filters/./ast/runemulation.lua:11: in local 'callback'
	.../quarto-cli/src/resources/filters/./ast/runemulation.lua:16: in upvalue 'run_emulated_filter_chain'
	.../quarto-cli/src/resources/filters/./ast/runemulation.lua:57: in function <.../quarto-cli/src/resources/filters/./ast/runemulation.lua:38>
stack traceback:
	...p/quarto-cli/src/resources/filters/./ast/customnodes.lua:150: in function 'run_emulated_filter'
	.../quarto-cli/src/resources/filters/./ast/runemulation.lua:11: in local 'callback'
	.../quarto-cli/src/resources/filters/./ast/runemulation.lua:16: in upvalue 'run_emulated_filter_chain'
	.../quarto-cli/src/resources/filters/./ast/runemulation.lua:57: in function <.../quarto-cli/src/resources/filters/./ast/runemulation.lua:38>
ERROR: Error
    at renderFiles (file:///Users/winston/nobackup/quarto-cli/src/command/render/render-files.ts:538:23)
    at async renderProject (file:///Users/winston/nobackup/quarto-cli/src/command/render/project.ts:263:23)
    at async Command.fn (file:///Users/winston/nobackup/quarto-cli/src/command/render/cmd.ts:211:26)
    at async Command.execute (file:///Users/winston/nobackup/quarto-cli/src/vendor/deno.land/x/cliffy@v0.25.4/command/command.ts:1790:7)
    at async quarto (file:///Users/winston/nobackup/quarto-cli/src/quarto.ts:122:3)
    at async file:///Users/winston/nobackup/quarto-cli/src/quarto.ts:154:5
(venv) 
```

**Comment by cscheid** [comment]
Hm. This is a different error, and it's now inside panflute. I don't know what I can do in this case 😬

**Comment by machow** [comment]
I have time set up to pair with Carlos on a lua filter next week, to hopefully resolve!

**Comment by machow** [comment]
I've merged / released the lua filter, which should resolve this (and allow people to use versions of quarto > 1.2!)
